# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1449, 962)
        MainWindow.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "QPushButton {\n"
            "    background-color: #6BA614;  /* Fondo más transparente */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px 5px;  /* Espaciado interno */\n"
            '    font: bold 12px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #3A5A40;  /* Cambio de color al pasar el mouse */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #2C4A34;  /* Cambio de color al hacer clic */\n"
            "    box-shadow: none;  /* Quita la sombra para efecto de presión */\n"
            "}\n"
            ""
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.StackedWidget.sizePolicy().hasHeightForWidth()
        )
        self.StackedWidget.setSizePolicy(sizePolicy)
        self.StackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.StackedWidget.setStyleSheet("")
        self.StackedWidget.setObjectName("StackedWidget")
        self.gridStackedWidgetPage1 = QtWidgets.QWidget()
        self.gridStackedWidgetPage1.setObjectName("gridStackedWidgetPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.gridStackedWidgetPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.framecamera = QtWidgets.QFrame(self.gridStackedWidgetPage1)
        self.framecamera.setStyleSheet(
            "background-color: rgb(155, 124, 255);\n"
            "background-color: rgb(255, 255, 255);"
        )
        self.framecamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framecamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framecamera.setObjectName("framecamera")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.framecamera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.framecamera)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LabelCamara = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelCamara.sizePolicy().hasHeightForWidth())
        self.LabelCamara.setSizePolicy(sizePolicy)
        self.LabelCamara.setMinimumSize(QtCore.QSize(0, 650))
        self.LabelCamara.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LabelCamara.setStyleSheet("background-color: rgb(177, 217, 137);a")
        self.LabelCamara.setText("")
        self.LabelCamara.setObjectName("LabelCamara")
        self.verticalLayout_3.addWidget(self.LabelCamara, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BtnSubir = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSubir.sizePolicy().hasHeightForWidth())
        self.BtnSubir.setSizePolicy(sizePolicy)
        self.BtnSubir.setMinimumSize(QtCore.QSize(200, 40))
        self.BtnSubir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BtnSubir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnSubir.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #6BA614;  /* Fondo más transparente */\n"
            "    border-radius: 2px;  /* Bordes redondeados */\n"
            "    padding: 5px 5px;  /* Espaciado interno */\n"
            '    font: bold 22px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #3A5A40;  /* Cambio de color al pasar el mouse */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #2C4A34;  /* Cambio de color al hacer clic */\n"
            "    box-shadow: none;  /* Quita la sombra para efecto de presión */\n"
            "}\n"
            ""
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("static/folder-upload.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnSubir.setIcon(icon)
        self.BtnSubir.setIconSize(QtCore.QSize(24, 24))
        self.BtnSubir.setObjectName("BtnSubir")
        self.gridLayout_3.addWidget(self.BtnSubir, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(
            300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.ImgDefecto = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImgDefecto.sizePolicy().hasHeightForWidth())
        self.ImgDefecto.setSizePolicy(sizePolicy)
        self.ImgDefecto.setMinimumSize(QtCore.QSize(200, 150))
        self.ImgDefecto.setMaximumSize(QtCore.QSize(200, 150))
        self.ImgDefecto.setStyleSheet("background-color: rgb(146, 226, 255);")
        self.ImgDefecto.setText("")
        self.ImgDefecto.setPixmap(QtGui.QPixmap("static/blog_placeholder.jpg"))
        self.ImgDefecto.setScaledContents(True)
        self.ImgDefecto.setObjectName("ImgDefecto")
        self.gridLayout_3.addWidget(
            self.ImgDefecto, 0, 0, 1, 1, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.BtnSalir = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSalir.sizePolicy().hasHeightForWidth())
        self.BtnSalir.setSizePolicy(sizePolicy)
        self.BtnSalir.setMinimumSize(QtCore.QSize(200, 40))
        self.BtnSalir.setMaximumSize(QtCore.QSize(140, 25))
        self.BtnSalir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnSalir.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #6BA614;  /* Fondo más transparente */\n"
            "    border-radius: 2px;  /* Bordes redondeados */\n"
            "    padding: 5px 5px;  /* Espaciado interno */\n"
            '    font: bold 22px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #3A5A40;  /* Cambio de color al pasar el mouse */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #2C4A34;  /* Cambio de color al hacer clic */\n"
            "    box-shadow: none;  /* Quita la sombra para efecto de presión */\n"
            "}\n"
            ""
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("static/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.BtnSalir.setIcon(icon1)
        self.BtnSalir.setIconSize(QtCore.QSize(24, 24))
        self.BtnSalir.setObjectName("BtnSalir")
        self.gridLayout_3.addWidget(self.BtnSalir, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.framecamera, 0, 0, 1, 1)
        self.framenavegacion = QtWidgets.QFrame(self.gridStackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.framenavegacion.sizePolicy().hasHeightForWidth()
        )
        self.framenavegacion.setSizePolicy(sizePolicy)
        self.framenavegacion.setMinimumSize(QtCore.QSize(350, 900))
        self.framenavegacion.setStyleSheet(
            "QLabel {\n"
            '    font: bold 20px "Georgia", serif;  /* Fuente aún más elegante y con mayor estilo */\n'
            "    background-color: #B1D989;  /* Fondo más transparente */\n"
            "    border: none;  /* Sin bordes en los lados */\n"
            "    border-radius: 5px;  /* Bordes más suaves */\n"
            "    color: #2b2b2b;  /* Color del texto */\n"
            "    padding: 5px 5px;  /* Espaciado más amplio */\n"
            "    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
            "    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
            "    text-align: center;  /* Centrar el texto */\n"
            "  \n"
            "}\n"
            ""
        )
        self.framenavegacion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framenavegacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framenavegacion.setObjectName("framenavegacion")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.framenavegacion)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(350, 250))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet(
            "QLabel {\n"
            "    background-color: rgb(255, 255, 255);\n"
            "    border: none;\n"
            "}\n"
            ""
        )
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("static/IconoTesisAc.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(
            self.label, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        self.toolButton = QtWidgets.QToolButton(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(350, 40))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 26px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Asegura que el texto esté centrado */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("static/tree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.toolButton.setIcon(icon2)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton, 0, QtCore.Qt.AlignHCenter)
        self.LabelNombre1 = QtWidgets.QLabel(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelNombre1.sizePolicy().hasHeightForWidth())
        self.LabelNombre1.setSizePolicy(sizePolicy)
        self.LabelNombre1.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelNombre1.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 20px "Arial";  /* Fuente más legible y tamaño aumentado */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Centra el texto */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        self.LabelNombre1.setObjectName("LabelNombre1")
        self.verticalLayout_2.addWidget(self.LabelNombre1, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem1)
        self.toolButton_2 = QtWidgets.QToolButton(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(350, 40))
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_2.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 26px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Asegura que el texto esté centrado */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("static/attribution-pencil.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.toolButton_2.setIcon(icon3)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_2.addWidget(self.toolButton_2, 0, QtCore.Qt.AlignHCenter)
        self.LabelNombre2 = QtWidgets.QLabel(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelNombre2.sizePolicy().hasHeightForWidth())
        self.LabelNombre2.setSizePolicy(sizePolicy)
        self.LabelNombre2.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelNombre2.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 20px "Arial";  /* Fuente más legible y tamaño aumentado */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Centra el texto */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        self.LabelNombre2.setObjectName("LabelNombre2")
        self.verticalLayout_2.addWidget(self.LabelNombre2, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.toolButton_3 = QtWidgets.QToolButton(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(350, 40))
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_3.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 26px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Asegura que el texto esté centrado */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("static/earth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.toolButton_3.setIcon(icon4)
        self.toolButton_3.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_2.addWidget(self.toolButton_3, 0, QtCore.Qt.AlignHCenter)
        self.LabelDistribucion = QtWidgets.QLabel(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LabelDistribucion.sizePolicy().hasHeightForWidth()
        )
        self.LabelDistribucion.setSizePolicy(sizePolicy)
        self.LabelDistribucion.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelDistribucion.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 20px "Arial";  /* Fuente más legible y tamaño aumentado */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Centra el texto */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        self.LabelDistribucion.setObjectName("LabelDistribucion")
        self.verticalLayout_2.addWidget(
            self.LabelDistribucion, 0, QtCore.Qt.AlignHCenter
        )
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem3)
        self.toolButton_4 = QtWidgets.QToolButton(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setMinimumSize(QtCore.QSize(350, 40))
        self.toolButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_4.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 26px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Asegura que el texto esté centrado */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("static/massage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.toolButton_4.setIcon(icon5)
        self.toolButton_4.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_2.addWidget(self.toolButton_4, 0, QtCore.Qt.AlignHCenter)
        self.LabelFloracion = QtWidgets.QLabel(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LabelFloracion.sizePolicy().hasHeightForWidth()
        )
        self.LabelFloracion.setSizePolicy(sizePolicy)
        self.LabelFloracion.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelFloracion.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 20px "Arial";  /* Fuente más legible y tamaño aumentado */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Centra el texto */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        self.LabelFloracion.setObjectName("LabelFloracion")
        self.verticalLayout_2.addWidget(self.LabelFloracion, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem4)
        self.toolButton_5 = QtWidgets.QToolButton(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setMinimumSize(QtCore.QSize(350, 40))
        self.toolButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_5.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 26px "Montserrat";  /* Fuente moderna */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Asegura que el texto esté centrado */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("static/chart-tree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.toolButton_5.setIcon(icon6)
        self.toolButton_5.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.verticalLayout_2.addWidget(self.toolButton_5, 0, QtCore.Qt.AlignHCenter)
        self.LabelFamiia = QtWidgets.QLabel(self.framenavegacion)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelFamiia.sizePolicy().hasHeightForWidth())
        self.LabelFamiia.setSizePolicy(sizePolicy)
        self.LabelFamiia.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelFamiia.setStyleSheet(
            "QToolButton {\n"
            "    background-color: #6BA614;  /* Color de fondo */\n"
            "    border-radius: 5px;  /* Bordes redondeados */\n"
            "    padding: 5px;  /* Espaciado interno */\n"
            '    font: bold 20px "Arial";  /* Fuente más legible y tamaño aumentado */\n'
            "    color: white;  /* Texto en blanco */\n"
            "    border: none;  /* Sin borde */\n"
            "    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
            "    text-align: center;  /* Centra el texto */\n"
            "}\n"
            "\n"
            "QToolButton::icon {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra el icono dentro del botón */\n"
            "}\n"
            "\n"
            "QToolButton::indicator {\n"
            "    qproperty-alignment: AlignCenter;  /* Centra cualquier indicador si aplica */\n"
            "}\n"
            ""
        )
        self.LabelFamiia.setObjectName("LabelFamiia")
        self.verticalLayout_2.addWidget(self.LabelFamiia, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout.addWidget(self.framenavegacion, 0, 1, 1, 1)
        self.StackedWidget.addWidget(self.gridStackedWidgetPage1)
        self.gridLayout_2.addWidget(self.StackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1449, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnSubir.setText(_translate("MainWindow", " Subir Imagen"))
        self.BtnSalir.setText(_translate("MainWindow", " Salir"))
        self.toolButton.setWhatsThis(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><br/></p></body></html>',
            )
        )
        self.toolButton.setText(_translate("MainWindow", " Nombre Común"))
        self.LabelNombre1.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:10pt;">TextLabel</span></p></body></html>',
            )
        )
        self.toolButton_2.setText(_translate("MainWindow", " Nombre Cientifico"))
        self.LabelNombre2.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:10pt;">cipress</span></p></body></html>',
            )
        )
        self.toolButton_3.setText(_translate("MainWindow", " Distribución Geografica"))
        self.LabelDistribucion.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:10pt;">TextLabel</span></p></body></html>',
            )
        )
        self.toolButton_4.setText(_translate("MainWindow", " Floración"))
        self.LabelFloracion.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:10pt;">TextLabel</span></p></body></html>',
            )
        )
        self.toolButton_5.setText(_translate("MainWindow", " Familia"))
        self.LabelFamiia.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:10pt;">TextLabel</span></p></body></html>',
            )
        )
